/**
      Returns the next number in an integer sequence whose elements are multiples of the value passed as argument
      to the constructor
      Example: factor = 1 initially, value = 5 then the sequence is 1*5, 2*5, 3*5 etc
      

 */
//-----------Start below here. To do: approximate lines of code = 1
// Make class MultipleSequence implement the Sequence interface 
class MultiplesSequence implements Sequence
//-----------------End here. Please do not remove this comment. Reminder: no changes outside the todo regions.
{
	private int number;
	private int factor;

	/**
            Constructor to initialize the multiplicative factor and number used to generate sequence elements
            @param nValue the value whose multiples are generated by the sequence
	 */   
	public MultiplesSequence(int nValue)
	{
		factor = 1;
		number = nValue;
	}

	/**
            Returns the next element in the sequence
            @return a sequence element
	 */
	//-----------Start below here. To do: approximate lines of code = 4
	// implement the Sequence interface (see Sequence.java)
	public int next(){
		int current = factor * number;
		this.factor++;
		return current;
	}
	
	
	
	
	
	//-----------------End here. Please do not remove this comment. Reminder: no changes outside the todo regions.
}